---
- name: Setup Web Server
  hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  tasks:
    - name: Install Python 3.8 (Amazon Linux 2)
      raw: amazon-linux-extras install -y python3.8 || true
      
    - name: Gather facts
      setup:
      
    - name: Install Docker
      shell: yum install -y docker

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose binary
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install Nginx
      shell: amazon-linux-extras install -y nginx1

    - name: Configure Nginx
      copy:
        content: |
          server {
              listen 80;
              server_name _;
              
              location / {
                  proxy_pass http://localhost:8080;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              }
          }
        dest: /etc/nginx/conf.d/default.conf

    - name: Start Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes

    - name: Copy webpage files
      copy:
        src: code/
        dest: /home/ec2-user/webpage/
        owner: ec2-user
        group: ec2-user

    - name: Run Docker Compose
      shell: cd /home/ec2-user/webpage && sg docker -c "/usr/local/bin/docker-compose up -d --build"

